# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reacttest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reacttest

  target 'reacttest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'reacttestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reacttest-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

end
